var device;
device = "SBH-300";
device = 89;
device = null;
device = 90.889;
device = true;
var celsius;
celsius = ["saumya", 29, true, null, 1812897.0098, 'a'];
celsius.push("RahulBist");
console.log(device);
console.log(celsius);
